# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mempool.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmempool.proto\x12\x07mempool\"\x8d\x02\n\x06UserOp\x12\x0e\n\x06sender\x18\x01 \x01(\x0c\x12\r\n\x05nonce\x18\x02 \x01(\x0c\x12\x11\n\tinit_code\x18\x03 \x01(\x0c\x12\x11\n\tcall_data\x18\x04 \x01(\x0c\x12\x16\n\x0e\x63\x61ll_gas_limit\x18\x05 \x01(\x0c\x12\x1e\n\x16verification_gas_limit\x18\x06 \x01(\x0c\x12\x1c\n\x14pre_verification_gas\x18\x07 \x01(\x0c\x12\x17\n\x0fmax_fee_per_gas\x18\x08 \x01(\x0c\x12 \n\x18max_priority_fee_per_gas\x18\t \x01(\x0c\x12\x1a\n\x12paymaster_and_data\x18\n \x01(\x0c\x12\x11\n\tsignature\x18\x0b \x01(\x0c\" \n\x0b\x41\x64\x64Response\x12\x11\n\tuserop_id\x18\x01 \x01(\x04\"&\n\nGetRequest\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\"/\n\x0bGetResponse\x12 \n\x07userOps\x18\x01 \x03(\x0b\x32\x0f.mempool.UserOp2m\n\x07MemPool\x12.\n\x03\x41\x64\x64\x12\x0f.mempool.UserOp\x1a\x14.mempool.AddResponse\"\x00\x12\x32\n\x03Get\x12\x13.mempool.GetRequest\x1a\x14.mempool.GetResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mempool_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USEROP._serialized_start=27
  _USEROP._serialized_end=296
  _ADDRESPONSE._serialized_start=298
  _ADDRESPONSE._serialized_end=330
  _GETREQUEST._serialized_start=332
  _GETREQUEST._serialized_end=370
  _GETRESPONSE._serialized_start=372
  _GETRESPONSE._serialized_end=419
  _MEMPOOL._serialized_start=421
  _MEMPOOL._serialized_end=530
# @@protoc_insertion_point(module_scope)
